fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.8.2
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: "ansible-lint"
        additional_dependencies:
          - ansible
