fail_fast: false
repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: conventional commit messages
        language: pygrep
        entry: '^(chore|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: (?![A-Z])(?![a-z]+(ed|ing)\s).*$'
    args:
      - --multiline
      - --negate # fails if the entry is NOT matched
    stages:
      - commit-msg

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.8.2
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: "ansible-lint"
        additional_dependencies:
          - ansible
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types: [ python ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  - repo: https://github.com/JangasCodingplace/commit-prefix-pre-commit
    rev: v0.0.3-beta
    hooks:
      - id: commit-prefix
        stages: [commit-msg]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
