---
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  empty-lines:
    max: 3
    level: error
  hyphens:
    level: error
  line-length:
    max: 200
  truthy:
    check-keys: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
