---
collections:
  - name: community.docker
    version: ">=3.0.2,<4.0.0"
  - name: community.general
    version: ">=6.0.0,<7.0.0"

roles:
  # Install external roles from Ansible Galaxy.
  - name: geerlingguy.docker
    version: "6.0.3"
  # - name: geerlingguy.firewall
  #   version: 2.5.0
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: morgangraphics.ansible_role_nvm
    version: "v1.5.1"
  - name: robertdebock.bootstrap
    version: 6.0.3
  - name: mrlesmithjr.mdadm
    version: "v0.1.2"
