---
# Limit local size to 500MB of logs per container
docker_log_driver: json-file
docker_log_options:
  max-file: "5"
  max-size: 100m

forest:
  image:
    name: ghcr.io/chainsafe/forest
    tag: latest-fat
  node_type: fullnode
  network: "calibnet"
  container_extra_args: []
  rust_log_level: "warn" # debug, info, warn, error, off
  f3_enabled_sidecar: false
  target_peer_count: 5000
  user: "{{ ansible_user }}"
  group: "{{ ansible_user }}"
  host:
    config_path: /home/{{ ansible_user }}/forest/config
    data_path: /home/{{ ansible_user }}/forest/forest_data
    scripts_path: /home/{{ ansible_user }}/forest/script
  container:
    config_path: /home/forest/config
    data_path: /home/forest/forest_data
    scripts_path: /script
  rpc:
    enabled: true
    port: 2345
    # Used by external nginx proxy
    host_port: 32345
  metrics:
    enabled: true
    port: 6116
    host_port: 36116
  import_libp2p_private_key: false
  libp2p_private_key: ""

nginx:
  host:
    dir: /home/{{ ansible_user }}/nginx
  container:
    dir: /etc/nginx
  metrics:
    auth_user: ""
    auth_password: ""

node_exporter:
  public_port: 39100
  port: 9100
