r2:
  endpoint_url: "https://2238a825c5aca59233eab1f221f7aefb.r2.cloudflarestorage.com"
  access_key_id: ""
  secret_access_key: ""
  bucket_name: "forest-archive"

external_disk:
  raid_devices: ""
  raid_device_name: md0
  raid_level: 0
  mount_point: /data
  filesystem_type: ext4

docker_compose:
  project_path: "/home/{{ ansible_user }}/forest-{{ forest.node_type }}-{{ network }}"

network: "testnet"

forest:
  image:
    name: ghcr.io/chainsafe/forest
    tag: latest-fat
  node_type: "archive"
  snapshots_format: v1
  log_level: "info" # debug, info, warning, error
  rust_log_level: "warn" # debug, info, warn, error, off
  host:
    config_path: "/home/{{ ansible_user }}/forest/{{ network }}/config"
    data_path: "/data/forest"
    snapshot_path: "/data/snapshots/{{ network }}"
    scripts_path: "/home/{{ ansible_user }}/forest/{{ network }}/scripts"
  container:
    config_path: "/home/forest/config"
    data_path: "/home/forest/data"
    scripts_path: "/scripts"
    snapshot_path: "/home/forest/snapshots"
    metrics_path: "/data/metrics"
  compute:
    enabled: false
    start_epoch: 0
    batch_size: 100
  validate_snapshots:
    enabled: false
    start_epoch: 0
  build_snapshots_historic:
    enabled: false
    start_epoch: 0
    delay: "{{ 24 * 60 * 60 }}"
    latest: false
  build_snapshots_latest:
    enabled: false
    start_epoch: 0
    delay: "{{ 6 * 60 * 60 }}"
    latest: false
  upload_snapshots:
    enabled: false
    start_epoch: 0
  metrics:
    port: 6116

rabbitmq:
  enabled: true
  user: "guest"
  password: "password"
  data_path: "/data/rabbitmq/{{ network }}"

grafana_alloy:
  enabled: true
  config_path: "/home/{{ ansible_user }}/grafana-alloy/{{ network }}"
  image: "grafana/alloy:latest"
  api_key: "GRAFANA_CLOUD_API_KEY"
  metrics:
    endpoint: "https://prometheus-prod-xx.grafana.net"
    username: "GRAFANA_CLOUD_METRICS_USERNAME"
  logs:
    endpoint: "https://logs-prod-xx.grafana.net"
    username: "GRAFANA_CLOUD_LOGS_USERNAME"

slack:
  token: "SLACK_TOKEN"
  channel: "#forest-dump"
