# R2 / Object Storage
r2:
  # S3-compatible endpoint for Cloudflare R2 or other object storage.
  endpoint_url: "https://2238a825c5aca59233eab1f221f7aefb.r2.cloudflarestorage.com"
  # Access key ID used for uploads.
  access_key_id: ""
  # Secret key used for uploads.
  secret_access_key: ""
  # Bucket name where snapshots are stored.
  bucket_name: "forest-archive"

# External Disk / Filesystem
external_disk:
  # List or device glob for RAID members (if any). Leave empty for single disk.
  raid_devices: []
  # RAID device name when `raid_devices` is used.
  raid_device_name: md0
  # RAID level (e.g., 0/1/5). Only used when `raid_devices` is set
  raid_level: 0
  # Mount point for the data disk that will hold archive and snapshots.
  mount_point: /data
  # Filesystem type used when formatting the disk or array.
  filesystem_type: ext4

# Docker Compose
docker_compose:
  # Path where Compose files and state are placed.
  project_path: "/home/{{ ansible_user }}/forest-{{ forest.node_type }}-{{ network }}"

# Filecoin network identifier (e.g., `mainnet`, `calibnet`). Used in names and configs.
network: "testnet"

# Forest configuration
forest:
  image:
    # Container image repository for Forest.
    name: ghcr.io/chainsafe/forest
    # Container image tag.
    tag: latest-fat
  # Node type descriptor used in naming; archive nodes keep full chain state.
  node_type: "archive"
  # Application log verbosity (debug, info, warning, error).
  log_level: "info" # debug, info, warning, error
  # Rust log filter passed to the process (debug, info, warn, error, off).
  rust_log_level: "warn" # debug, info, warn, error, off
  # Enables F3 sidecar FFI if required.
  f3_enabled_sidecar: false
  # Target number of peers to connect to.
  target_peer_count: 5000
  # Extra CLI args for the Forest process; `--no-gc` recommended for snapshotters.
  container_extra_args:
    - "--no-gc"
  host:
    # Forest config directory on host.
    config_path: "/home/{{ ansible_user }}/forest/{{ network }}/config"
    # Forest data directory on host.
    data_path: "/data/forest"
    # Snapshot output directory on host.
    snapshot_path: "/data/snapshots/{{ network }}"
    # Helper scripts directory on host.
    scripts_path: "/home/{{ ansible_user }}/forest/{{ network }}/scripts"
  container:
    # Config directory inside container.
    config_path: "/home/forest/config"
    # Data directory inside container.
    data_path: "/home/forest/data"
    # Scripts directory inside container.
    scripts_path: "/scripts"
    # Snapshot output path inside container.
    snapshot_path: "/home/forest/snapshots"
    # Metrics/logs path inside container.
    metrics_path: "/data/metrics"
  compute:
    # Enable compute-state job service.
    enabled: false
    # Starting epoch for compute-state.
    start_epoch: 0
    # Batch size for compute-state processing.
    batch_size: 100
  build_snapshots_historic:
    # Enable historic snapshots builder.
    enabled: false
    # Starting epoch for historic snapshot generation.
    start_epoch: 0
    # Delay between historic snapshot runs in seconds.
    delay: "{{ 24 * 60 * 60 }}"
  build_snapshots_latest:
    # Enable periodic latest snapshot builder.
    enabled: false
    # Snapshot format/version for latest snapshots.
    format: "v1"
    # Delay between latest snapshot runs in seconds.
    delay: "{{ 6 * 60 * 60 }}"
  upload_snapshots:
    # Enable uploader service to push snapshots to object storage.
    enabled: false
  validate_snapshots:
    # Enable validator service to verify produced snapshots.
    enabled: false
  metrics:
    # Metrics port exposed by Forest.
    port: 6116
  # Whether to import a provided libp2p private key.
  import_libp2p_private_key: false
  # The libp2p private key material (handle securely).
  libp2p_private_key: ""

# RabbitMQ
rabbitmq:
  # Whether to deploy RabbitMQ alongside the pipeline.
  enabled: true
  #  RabbitMQ username.
  user: "guest"
  # RabbitMQ password.
  password: "password"
  # Host path for RabbitMQ data.
  data_path: "/data/rabbitmq/{{ network }}"

# # Grafana Alloy (Metrics/Logs Shipping)
grafana_alloy:
  # Whether to deploy Grafana Alloy sidecar.
  enabled: true
  # Host path for Alloy configs.
  config_path: "/home/{{ ansible_user }}/grafana-alloy/{{ network }}"
  # Grafana Alloy container image.
  image: "grafana/alloy:latest"
  # Grafana Cloud API key used for remote_write.
  api_key: "GRAFANA_CLOUD_API_KEY"
  metrics:
    # Grafana Cloud Prometheus endpoint.
    endpoint: "https://prometheus-prod-xx.grafana.net"
    # Prometheus instance/user ID.
    username: "GRAFANA_CLOUD_METRICS_USERNAME"
  logs:
    # Grafana Cloud Logs endpoint.
    endpoint: "https://logs-prod-xx.grafana.net"
    # Logs instance/user ID.
    username: "GRAFANA_CLOUD_LOGS_USERNAME"

# Slack Notifications
slack:
  # Bot token used to post notifications.
  token: "SLACK_TOKEN"
  # Default channel for notifications.
  channel: "#forest-dump"
