---
- name: Configure disks
  block:
    - name: Create RAID array from extra disks
      ansible.builtin.include_role:
        name: mrlesmithjr.mdadm
      vars:
        mdadm_arrays:
          - name: "{{ external_disk.raid_device_name }}"
            devices: "{{ external_disk.raid_devices }}"
            filesystem: "{{ external_disk.filesystem_type }}"
            level: "{{ external_disk.raid_level }}"
            mountpoint: "{{ external_disk.mount_point }}"
            state: present
            options: "{{ external_disk.mount_options }}"

    - name: Grant permissions to the RAID array
      ansible.builtin.file:
        path: "{{ external_disk.mount_point }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        state: directory
