---
- name: Ensure Forest node directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ forest.host.scripts_path }}"
    - "{{ forest.host.config_path }}"
    - "{{ forest.host.data_path }}"

- name: Ensure Lotus node directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ lotus.host.data_path }}"
    - "{{ lotus.host.parameter_cache }}"
    - "{{ lotus.host.parent_cache }}"

- name: Ensure forest token exists
  block:
    - name: Create token
      ansible.builtin.command:
        cmd: "touch {{ forest.host.data_path }}/token"
        creates: "{{ forest.host.data_path }}/token"

    - name: Set token permissions
      ansible.builtin.file:
        path: "{{ forest.host.data_path }}/token"
        state: file
        owner: "{{ ansible_user }}"
        mode: '0600'

- name: Deploy forest entrypoint
  ansible.builtin.template:
    src: "forest/forest.sh.j2"
    dest: "{{ forest.host.scripts_path }}/forest.sh"
    owner: "{{ ansible_user }}"
    mode: '0755'
  notify: Restart forest

- name: Copy forest configs
  ansible.builtin.template:
    src: "forest/{{ item }}.j2"
    dest: "{{ forest.host.config_path }}/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - config.toml
    - filter-list.txt
  notify: Restart forest
