---
- name: Ensure Job directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ forest.host.scripts_path }}"
    - "{{ forest.host.snapshot_path }}"
    - "{{ forest.host.snapshot_archive_path }}"

- name: Python packages
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ forest.host.scripts_path }}/"
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop: "{{ lookup('fileglob', '*.py', wantlist=True) }}"
  loop_control:
    label: "{{ item }}"
