---
- name: Configure External Disks
  become: true
  ansible.builtin.import_tasks: disks.yml
  when: external_disk.raid_devices | length > 0

- name: Configure Forest Node
  ansible.builtin.import_tasks: forest-node.yml

- name: Configure RabbitMQ
  ansible.builtin.import_tasks: rabbitmq.yml

- name: Configure Monitoring
  ansible.builtin.import_tasks: monitoring.yml

- name: Configure jobs
  ansible.builtin.import_tasks: jobs.yml

- name: Configure Docker Compose
  ansible.builtin.import_tasks: compose.yml
