---
- name: Install docker + docker-compose
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Docker Python wrapper
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Install aliases for docker
  ansible.builtin.copy:
    src: files/docker-aliases.sh
    dest: "/home/{{ bootstrap_user }}/.bash_aliases"
    mode: '0644'

- name: Schedule daily prune of docker
  when: docker_daily_prune
  ansible.builtin.cron:
    name: docker-prune
    special_time: daily
    job: >
      docker system prune -af  --filter "until=$((30*24))h"

- name: Get global IPv6 info
  ansible.builtin.set_fact:
    ipv6_info: "{{ hostvars[inventory_hostname]['ansible_' + ansible_default_ipv6.interface]['ipv6'] | selectattr('scope', 'equalto', 'global') | first }}"

- name: Configure Docker daemon for IPv6
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: '0644'
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "{{ ipv6_info.address }}/80"
      }
  notify: Restart docker
